[package]
name = "source_view_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sourceview5 = "0.2.0"
anyhow = "1.0.44"

[dependencies.gtk]
version = "0.2"
package = "gtk4"


